# Generated by Django 3.1.7 on 2021-02-28 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TopSongPoularity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=220)),
                ('artist', models.CharField(max_length=220)),
                ('top_genre', models.CharField(max_length=220)),
                ('year', models.IntegerField()),
                ('added', models.DateField()),
                ('pop', models.IntegerField()),
                ('duration', models.IntegerField()),
                ('country', models.CharField(max_length=100)),
            ],
        ),
    ]
