# Generated by Django 3.1.7 on 2021-03-05 18:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='topsongpoularity',
            name='added',
        ),
    ]
